#######################################   CHARTA   ########################################
#          Normaliza gráficamente los ficheros de texto plano para mejorar los            #
#                       análisis estilométricos de los testimonios                        #
#  Proyecto 7PartidasDigital "Edición crítica digital de las Siete Partidas de Alfonso X" #
#        Proyecto financiado por el MINECO, referencia FFI2016-75014-P AEI-FEDER, EU      #
#                Universidad de Valladolid -- IP José Manuel Fradejas Rueda               #
#                              https://7partidas.hypotheses.org/                          #
#                             https://github.com/7PartidasDigital                         #
#                         Este material se distribuye con una licencia                    #
#                                            MIT                                          #
#                                         v. 1.0.0                                        #

charta <- function(x){
entrada <- tolower(entrada)
#corregido <- stringr::str_replace_all(entrada, "^\\d+\\.{0,1}.*", "")
corregido <- stringr::str_replace_all(entrada, "nrr", "nr")
corregido <- stringr::str_replace_all(corregido, "\\bconu[ji]", "convi")
corregido <- stringr::str_replace_all(corregido, "([bcdfghlmnpqrstv])y([bcdfghlmnpqrstv])", "\\1i\\2")
corregido <- stringr::str_replace_all(corregido, "mm", "m")
corregido <- stringr::str_replace_all(corregido, "\\brr", "r")
corregido <- stringr::str_replace_all(corregido, "n([pb])", "m\\1")
corregido <- stringr::str_replace_all(corregido, "nn", "ñ")
corregido <- stringr::str_replace_all(corregido, "ñj", "ñi")
corregido <- stringr::str_replace_all(corregido, "ñ[^aeiou]", "n")
corregido <- stringr::str_replace_all(corregido, "ñobl", "nobl")
corregido <- stringr::str_replace_all(corregido, "ss", "s")
corregido <- stringr::str_replace_all(corregido, "^([bdnmpqgrst])v", "\\1u")
corregido <- stringr::str_replace_all(corregido, "ff", "f")
corregido <- stringr::str_replace_all(corregido, "\\&", "e")
corregido <- stringr::str_replace_all(corregido, "xpi", "cri")
corregido <- stringr::str_replace_all(corregido, "ivy", "jui")
corregido <- stringr::str_replace_all(corregido, "chri", "cri")
corregido <- stringr::str_replace_all(corregido, "ty", "ti")
corregido <- stringr::str_replace_all(corregido, "\\b[ij][h]*e([sr])u", "je\\1u")
corregido <- stringr::str_replace_all(corregido, "ç([ei])", "c\\1")
corregido <- stringr::str_replace_all(corregido, "seer", "ser")
corregido <- stringr::str_replace_all(corregido, "vn", "un")
corregido <- stringr::str_replace_all(corregido, "ff", "f")
corregido <- stringr::str_replace_all(corregido, " i ", " e ")
corregido <- stringr::str_replace_all(corregido, " vs", " us")
corregido <- stringr::str_replace_all(corregido, "\\bvua", "uva")
corregido <- stringr::str_replace_all(corregido, "\\bvuo", "uvo")
corregido <- stringr::str_replace_all(corregido, "avn", "aun")
corregido <- stringr::str_replace_all(corregido, "\\bdesuj", "desvi")
corregido <- stringr::str_replace_all(corregido, "rayz", "raiz")
corregido <- stringr::str_replace_all(corregido, "\\bfuy([^aeiou])\\b", "fui\\1")
corregido <- stringr::str_replace_all(corregido, "\\bdeley", "delei")
corregido <- stringr::str_replace_all(corregido, "desuj", "desvi")
corregido <- stringr::str_replace_all(corregido, "olui", "olvi")
corregido <- stringr::str_replace_all(corregido, "\\b([aeio])u", "\\1v")
corregido <- stringr::str_replace_all(corregido, "\\bsalu([aeio])", "salv\\1")
corregido <- stringr::str_replace_all(corregido, "\\balue", "alve")
corregido <- stringr::str_replace_all(corregido, "olui", "olvi")
corregido <- stringr::str_replace_all(corregido, "cuy([dt])", "cui\\1")
corregido <- stringr::str_replace_all(corregido, "ay([bcdfghjklmnpqrst])", "ai\\1")
corregido <- stringr::str_replace_all(corregido, "\\bn([ijo])n\\b", "n\\1")
corregido <- stringr::str_replace_all(corregido, "([aeiou])u([aeiou])", "\\1v\\2")
corregido <- stringr::str_replace_all(corregido, "([aeiou])lu([aeiou])", "\\1v\\2")
corregido <- stringr::str_replace_all(corregido, "([^d][eo])s([cç][ei])", "\\1\\2")
corregido <- stringr::str_replace_all(corregido, "([^lu]e)y([^aieou\\b])", "\\1i\\2") # Falla con grey, y rey
corregido <- stringr::str_replace_all(corregido, "rei\\b", "rey")
corregido <- stringr::str_replace_all(corregido, "([aeou])i([aeou])", "\\1j\\2") # No lo tengo claro aún
corregido <- stringr::str_replace_all(corregido, "([qg])uj", "\\1ui")
corregido <- stringr::str_replace_all(corregido, "\\by([^aeiou])", "i\\1")
corregido <- stringr::str_replace_all(corregido, "oy([dtrgms])", "oi\\1")
corregido <- stringr::str_replace_all(corregido, "sy", "si")
corregido <- stringr::str_replace_all(corregido, "\\benuest", "envest")
corregido <- stringr::str_replace_all(corregido, "\\pegui", "peguj")
corregido <- stringr::str_replace_all(corregido, "\\bs[ij]eru", "sierv")
corregido <- stringr::str_replace_all(corregido, "c[ij]ent\\b", "cien")
corregido <- stringr::str_replace_all(corregido, "dent\\b", "dende") # cabe la posibilidad de que sea diente, pero...
corregido <- stringr::str_replace_all(corregido, "ent\\b", "ente")
corregido <- stringr::str_replace_all(corregido, "honr", "onr")
corregido <- stringr::str_replace_all(corregido, "\\bi[uv]an", "juan")
corregido <- stringr::str_replace_all(corregido, "[ijy]uañ", "ivañ")
corregido <- stringr::str_replace_all(corregido, "\\bnome", "nombre")
corregido <- stringr::str_replace_all(corregido, "\\bhome\\b", "ome")
corregido <- stringr::str_replace_all(corregido, "\\bhomes\\b", "omes")
corregido <- stringr::str_replace_all(corregido, "([ie])ru[ji]", "\\1rvi")
corregido <- stringr::str_replace_all(corregido, "aur[ji]", "avri")
corregido <- stringr::str_replace_all(corregido, "\\bujese", "uviese")
corregido <- stringr::str_replace_all(corregido, "\\bgran[dt]\\b", "gran")
corregido <- stringr::str_replace_all(corregido, "\\bi[uv]ez", "juez")
corregido <- stringr::str_replace_all(corregido, "\\bi[uv]yz", "juiz")
corregido <- stringr::str_replace_all(corregido, "\\b[ji][vu]y", "jui")
corregido <- stringr::str_replace_all(corregido, "\\bperiu", "perju")
corregido <- stringr::str_replace_all(corregido, "\\biu([dz])", "ju\\1")
corregido <- stringr::str_replace_all(corregido, "gun[dt]\\b", "gun")
corregido <- stringr::str_replace_all(corregido, "\\blei\\b", "ley")
corregido <- stringr::str_replace_all(corregido, "\\bpley", "plei")
corregido <- stringr::str_replace_all(corregido, "\\biamas", "jamas")
corregido <- stringr::str_replace_all(corregido, "\\bi[uv]", "ju")
corregido <- stringr::str_replace_all(corregido, "\\bive", "jue")
corregido <- stringr::str_replace_all(corregido, "\\bini[uv]s", "injus")
corregido <- stringr::str_replace_all(corregido, "\\bdesuso\\b", "de suso")
corregido <- stringr::str_replace_all(corregido, "\\bdeyuso\\b", "de yuso")
corregido <- stringr::str_replace_all(corregido, " i ", " y ")
corregido <- stringr::str_replace_all(corregido, "veer", "ver")
#corregido <- stringr::str_replace_all(corregido, "\\.[ijvxlc]+\\.", "")
corregido <- corregido[corregido !=""]
}
