# Convierto los fichero xml en txt


texto <- readLines("SP-IDI-LIM.xml")
limpio <- gsub("^\\s+", "", texto)
limpio <- gsub("^<[pc]b.*$", "", limpio)
limpio <- gsub("^<fw.*$", "", limpio)
limpio <- limpio[limpio != ""]
limpio <- paste(limpio, collapse = "")
limpio <- gsub("<div", "\n<div", limpio)
limpio <- gsub("<p>", "\n<p>", limpio)
limpio <- gsub("<head>", "\n<head>", limpio)
limpio <- gsub("</?item>", " ", limpio)
limpio <- gsub("</?list>", " ", limpio)
limpio <- gsub("</?unclear>", " ", limpio)
limpio <- gsub('<hi rend="init\\d+">', "", limpio)
limpio <- gsub('</hi>', "", limpio)
limpio <- gsub('</?sic>', "", limpio)
limpio <- gsub('-<lb break="no"/>', "", limpio)
limpio <- gsub('<lb/>', " ", limpio)
limpio <- gsub('amp;', "", limpio)
limpio <- gsub('</.*?>', "", limpio)
writeLines(limpio, "chapuza.txt")
limpio <- readLines("chapuza.txt")
limpio <- gsub('<div n="(.*)" type.*$', "<div>\\1", limpio)
limpio <- gsub('\\s{2,10}', " ", limpio)
limpio <- paste(limpio, collapse = "")
limpio <- gsub('<head> ?', "\t", limpio)
limpio <- gsub('<p> ?', "\t", limpio)
limpio <- gsub('<div>', "\n", limpio)
writeLines(limpio, "chapuza.txt")
